// Declarative state/event diagrams. No supplied markup or executable code is accepted.
const ID = /^[a-z][a-z0-9-]*$/;
const object = (v) => v && typeof v === 'object' && !Array.isArray(v);
export function validateStateMachine(v, where, { add, ids }) {
  const error = (key, text) => add(`${where}.${key}`, text);
  if (!object(v)) { error('', 'stateMachine はオブジェクト'); return; }
  const keys = (value, allowed, at) => { for (const k of Object.keys(value)) if (!allowed.includes(k)) error(at, `未対応の項目: ${k}`); };
  keys(v, ['id','title','initial','legend','description','width','height','nodes','transitions','paths','decorations','participants'], '');
  if (!ID.test(v.id || '')) error('id', 'id は英小文字から始まる kebab-case');
  // Reserve every generated DOM id, including SVG descriptions and markers.
  for (const id of [`state-machine-${v.id}`, `state-machine-${v.id}-arrow`, `state-machine-${v.id}-desc`]) {
    if (ids.has(id)) error('id', `stateMachine の id が重複: ${id}`);
    ids.add(id);
  }
  for (const k of ['title','description','legend']) if (typeof v[k] !== 'string' || !v[k].trim()) error(k,'空でない文字列が必要');
  for (const k of ['width','height']) if (!Number.isFinite(v[k]) || v[k] < 1 || v[k] > 4000) error(k,'1〜4000 の数値が必要');
  const list = (k, required = false) => { if (!Array.isArray(v[k]) || (required && !v[k].length)) { error(k,'配列が必要'); return []; } return v[k]; };
  const nodes = list('nodes',true), transitions = list('transitions',true), actors = list('participants',true);
  const nodeIds = new Set(), transitionIds = new Set(), actorIds = new Set();
  const identify = (item, set, at) => { if (!ID.test(item.id || '') || set.has(item.id)) error(at,'id が不正または重複'); set.add(item.id); };
  const text = (value, at) => { if (typeof value !== 'string' || !value.trim()) error(at,'空でない文字列が必要'); };
  const box = (item, at) => { for (const k of ['x','y','width','height']) if (!Number.isFinite(item[k]) || item[k] < 0 || ((k==='width'||k==='height') && item[k]===0)) error(at,`${k} は有効な座標・寸法にする`); if (item.x+item.width>v.width || item.y+item.height>v.height) error(at,'図の寸法からはみ出している'); };
  actors.forEach((a,i)=> { const at=`participants[${i}]`; if (!object(a)) {error(at,'オブジェクトが必要');return;} keys(a,['id','label'],at);identify(a,actorIds,at);text(a.label,at); });
  nodes.forEach((n,i)=>{const at=`nodes[${i}]`;if(!object(n)){error(at,'オブジェクトが必要');return;}keys(n,['id','label','description','x','y','width','height'],at);identify(n,nodeIds,at);text(n.label,at);text(n.description,at);box(n,at);if(n.width<100||n.height<64)error(at,"node は幅 100・高さ 64 以上にする");});
  if (!nodeIds.has(v.initial)) error('initial','nodes にある id が必要');
  transitions.forEach((t,i)=>{const at=`transitions[${i}]`;if(!object(t)){error(at,'オブジェクトが必要');return;}keys(t,['id','from','to','event','result','x','y','width','height','messages','local'],at);identify(t,transitionIds,at);box(t,at);for(const k of ['from','to'])if(!nodeIds.has(t[k]))error(at,`${k} の状態が無い`);text(t.event,at);text(t.result,at);if(t.local!=null)text(t.local,at);if(!Array.isArray(t.messages))error(at,'messages は配列');else t.messages.forEach((m,j)=>{if(!object(m)){error(at,'message はオブジェクト');return;}keys(m,['from','to','label'],at);for(const k of ['from','to'])if(!actorIds.has(m[k]))error(at,`messages[${j}] の参加者が無い`);text(m.label,at);});});
  const path = (d, at) => {if(typeof d!=='string'||!d.trim()||!/^[MmLlHhVvCcSsQqTtAaZz0-9eE+.,\s-]+$/.test(d))error(at,'d は SVG path の座標だけを書く');};
  list('paths').forEach((p,i)=>{const at=`paths[${i}]`;if(!object(p)){error(at,'オブジェクトが必要');return;}keys(p,['d','transitions','arrow'],at);path(p.d,at);if(p.arrow!=null&&typeof p.arrow!=='boolean')error(at,'arrow は boolean');if(!Array.isArray(p.transitions)||!p.transitions.length||p.transitions.some(id=>!transitionIds.has(id)))error(at,'既存 transition id の空でない配列が必要');});
  list('decorations').forEach((d,i)=>{const at=`decorations[${i}]`;if(!object(d)){error(at,'オブジェクトが必要');return;}keys(d,['d','text','x','y'],at);if(d.d!=null){path(d.d,at);if(d.text!=null)error(at,'d と text は併記しない');}else{text(d.text,at);for(const k of ['x','y'])if(!Number.isFinite(d[k]))error(at,'text の座標が必要');}});
}
export function renderStateMachine(v, esc) {
  const id=`state-machine-${v.id}`, initial=v.nodes.find(n=>n.id===v.initial);
  const fo=(g,body)=>`<foreignObject x="${g.x}" y="${g.y}" width="${g.width}" height="${g.height}">${body}</foreignObject>`;
  const paths=v.paths.map(p=>`<g class="rsv-path" data-transitions="${esc(p.transitions.join(' '))}"><path class="rsv-wire" d="${esc(p.d)}"${p.arrow?' marker-end="url(#'+id+'-arrow)"':''}></path></g>`).join('');
  const decorations=v.decorations.map(d=>d.d?`<path class="rsv-diamond" d="${esc(d.d)}"></path>`:`<text class="rsv-send-label" x="${d.x}" y="${d.y}" text-anchor="middle">${esc(d.text)}</text>`).join('');
  const events=v.transitions.map(t=>fo(t,`<div xmlns="http://www.w3.org/1999/xhtml" class="rsv-action-wrap"><button type="button" class="rsv-action" data-transition="${esc(t.id)}" aria-disabled="true" tabindex="-1">${esc(t.result)}</button></div>`)).join('');
  const nodes=v.nodes.map(n=>fo(n,`<button xmlns="http://www.w3.org/1999/xhtml" type="button" class="rsv-node" style="width:${n.width-4}px;height:${n.height-6}px" data-node-state="${esc(n.id)}" data-current="${n.id===v.initial}" aria-label="${esc(n.label)}。${esc(n.description)}"><span class="rsv-node-name">${esc(n.label)}</span><span class="rsv-node-desc">${esc(n.description)}</span><span class="rsv-node-action" aria-hidden="true">ここから試す<span>↗</span></span></button>`)).join('');
  const data=JSON.stringify(v).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');
  const staticRows=v.transitions.map(t=>`<li>${esc(v.nodes.find(n=>n.id===t.from).label)} → ${esc(v.nodes.find(n=>n.id===t.to).label)}：${esc(t.event)} · ${esc(t.result)}${t.local?' · '+esc(t.local):''}<ul>${t.messages.map(m=>`<li>${esc(v.participants.find(a=>a.id===m.from).label)} → ${esc(v.participants.find(a=>a.id===m.to).label)}：${esc(m.label)}</li>`).join('')}</ul></li>`).join('');
  return `<div class="rsv" id="${id}" data-state-machine="" data-layout="horizontal" data-initial-state="${esc(v.initial)}" data-start-state="${esc(v.initial)}" data-current-state="${esc(v.initial)}" style="--sm-width:${v.width}px;--sm-height:${v.height}px" role="group" aria-label="${esc(v.title)}"><script type="application/json" data-state-machine-source>${data}</script><div class="rsv-toolbar"><button type="button" class="rsv-reset" data-reset-initial>初期状態 (= ${esc(initial.label)}) に戻す</button><div class="rsv-layout" role="group" aria-label="図の並び方"><button type="button" data-layout-option="horizontal" aria-pressed="true">横並び</button><button type="button" data-layout-option="vertical" aria-pressed="false">縦並び</button></div></div><div class="rsv-workspace"><div class="rsv-columns"><section class="rsv-diagram" aria-label="状態遷移"><div class="rsv-diagram-head"><h3>状態遷移</h3><p class="rsv-map-legend">${esc(v.legend)}</p><p class="rsv-initial">開始：<span data-start-label>${esc(initial.label)}</span></p></div><div class="rsv-viewport" tabindex="0" aria-label="状態遷移図。必要に応じて左右にスクロールできます"><svg class="rsv-map" width="${v.width}" height="${v.height}" viewBox="0 0 ${v.width} ${v.height}" role="group" aria-label="${esc(v.title)}" aria-describedby="${id}-desc" xmlns="http://www.w3.org/2000/svg"><desc id="${id}-desc">${esc(v.description)}</desc><defs><marker id="${id}-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10Z" fill="context-stroke"></path></marker></defs>${paths}${decorations}${events}${nodes}</svg></div><p class="rsv-status" role="status" aria-live="polite" aria-atomic="true">現在：<span data-current-label>${esc(initial.label)}</span>。状態の説明：<span data-current-description>${esc(initial.description)}</span></p></section><section class="rsv-history" aria-label="操作と通信のシーケンス"><h4>操作と通信の履歴</h4><p class="rsv-count" data-sequence-count>実行 0 回 · 通信 0 件</p><div class="rsv-sequence-viewport"><div class="rsv-timeline"><div class="rsv-actors" style="display:grid;grid-template-columns:repeat(${v.participants.length},minmax(0,1fr))" role="group" aria-label="通信の参加者">${v.participants.map(a=>`<span>${esc(a.label)}</span>`).join('')}</div><ol class="rsv-records" data-sequence-rows aria-label="実行順の操作と通信"><li class="rsv-record"><div class="rsv-caption">開始 · ${esc(initial.label)}</div><p class="rsv-local">まだ操作を実行していません。</p></li></ol></div></div></section></div></div><details class="rsv-static" open><summary>状態遷移と通信の一覧</summary><ol>${staticRows}</ol></details></div>`;
}
